data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_files: data.csv

  split_data_dir: slit_data_dir
  train_data: train.csv

  test_data: test.csv

  model_dir: model_dir
  model_filename: ElasticNet.model

  score_dir: score_dir
  score_file_name: score_file.json
